# This file was generated by GoReleaser. DO NOT EDIT.
class Fvm < Formula
  desc "Flutter version management tool"
  homepage "https://github.com/leoafarias/fvm"
  url "https://github.com/leoafarias/fvm/releases/download/v0.1.5/fvm_0.1.5_Darwin_x86_64.tar.gz"
  version "0.1.5"
  sha256 "c55eee59e8f6e54f94e27603585a637bf067fabcc30aa383736cd22f768b4c83"
  
  depends_on "git"

  def install
    bin.install "fvm"
  end
end
