# This file was generated by GoReleaser. DO NOT EDIT.
class Fvm < Formula
  desc "Flutter version management tool"
  homepage "https://github.com/leoafarias/fvm"
  url "https://github.com/leoafarias/fvm/releases/download/v0.1.13/fvm_0.1.13_Darwin_x86_64.tar.gz"
  version "0.1.13"
  sha256 "f4be7bbe340a5ccad15b4083ef19e9c000dcf029f9e5e7b52cbabd23b45961ac"
  
  depends_on "git"

  def install
    bin.install "fvm"
  end
end
