# This file was generated by GoReleaser. DO NOT EDIT.
class Fvm < Formula
  desc ""
  homepage ""
  url "https://github.com/leoafarias/fvm/releases/download/v0.1.3/fvm_0.1.3_Darwin_x86_64.tar.gz"
  version "0.1.3"
  sha256 "db23e49e0e806afe8cb1758ad760481e03d9997b274dc1fb298de7deeb5bbed4"

  def install
    bin.install "fvm"
  end
end
