# This file was generated by GoReleaser. DO NOT EDIT.
class Fvm < Formula
  desc "Flutter version management tool"
  homepage "https://github.com/leoafarias/fvm"
  url "https://github.com/leoafarias/fvm/releases/download/v0.3.0/fvm_0.3.0_darwin_amd64.tar.gz"
  version "0.3.0"
  sha256 "e697d9fe8d6f3cb3c9e202d6e5ac7682dc4ae3e8fc6f859d03c19da72a58128f"
  
  depends_on "git"

  def install
    bin.install "fvm"
  end
end
